apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: docker
    image: docker
    comand:
    - cat
    tty: true 
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.16.0
    comand:
    - cat
    tty: true
